In [12]:
import pandas as pd 
import numpy as np

In [13]:
df=pd.read_csv("housing.csv")
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [14]:
df["income_cat"]=pd.cut(df["median_income"],bins=[0,1.5,2.5,3.5,4.5,5.5,6,np.inf],labels=[1,2,3,4,5,6,7])

In [15]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,income_cat
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY,7
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY,7
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY,7
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY,6
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY,4

In [16]:
from sklearn.model_selection import StratifiedShuffleSplit # can do multiple splits

In [17]:
sss=StratifiedShuffleSplit(n_splits=1,test_size=0.2,random_state=42)
for train_idx,test_idx in sss.split(df,df["income_cat"]):
    train_set=df.iloc[train_idx]
    test_set=df.iloc[test_idx]

In [18]:
#droping "income_cat" column now

In [19]:
df=train_set.copy()

In [20]:
df.drop("income_cat",axis=1,inplace=True)

In [22]:
#Before Handling missing data: remove the main feature
# here it is "median_house_value"

In [50]:
housing=df.drop("median_house_value",axis=1)
housing_label=df["median_house_value"].copy()

In [51]:
housing.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
17751,-121.84,37.33,26.0,1934.0,408.0,2059.0,416.0,3.6765,<1H OCEAN
12609,-121.49,38.51,30.0,3166.0,607.0,1857.0,579.0,3.1768,INLAND
1030,-120.25,38.55,15.0,4403.0,891.0,1103.0,433.0,3.0125,INLAND
9844,-121.90,36.59,42.0,2689.0,510.0,1023.0,459.0,4.6182,NEAR OCEAN
1253,-122.01,39.21,50.0,1592.0,372.0,781.0,307.0,2.2679,INLAND

In [52]:
#now lets handle missing value
housing.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        162
population              0
households              0
median_income           0
ocean_proximity         0
dtype: int64

In [53]:
#you can drop the rows or column but here i am using SimpleImputer
from sklearn.impute import SimpleImputer
housing_num=housing.select_dtypes(include=[np.number])
imputer=SimpleImputer(strategy="median")
X=imputer.fit_transform(housing_num)

In [54]:
imputer.statistics_ #Values you are going to use

array([-118.51  ,   34.26  ,   29.    , 2125.    ,  433.    , 1165.    ,
        409.    ,    3.5346])

In [55]:
housing_num=pd.DataFrame(X,columns=housing_num.columns,index=housing_num.index)

In [57]:
housing_num.isnull().sum() #All missing data handled

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
dtype: int64